





apiVersion: apps/v1
kind: Deployment
metadata:
  name: token-service-deployment
  labels: 
    app : token-service

spec :
  replicas: 2
  selector :
    matchLabels:
      app: token-service

  template: 
    metadata:
      labels:
        app: token-service
    
    spec :
      containers:
        - name : token-service
          image : morwen/token-service:latest
          ports : 
           - containerPort : 8001
