
apiVersion : v1
kind : Service 
metadata:
  name: token-service
  labels: 
    app : token-service

spec : 
  type : NodePort
  ports : 
    - port : 8001
      targetPort : 8001
      nodePort : 30001
  selector : 
    app : token-service
      